# Generated by Django 4.2.6 on 2023-11-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90)),
                ('file', models.FileField(upload_to='print_files/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('B&W', 'Black and White'), ('Color', 'Color')], max_length=5)),
                ('orientation', models.CharField(choices=[('SP', 'Single Page'), ('DP', 'Double Page')], max_length=5)),
            ],
        ),
    ]
