# Generated by Django 4.2.6 on 2023-11-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_order_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
