# Generated by Django 4.2.6 on 2023-11-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_order_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orientation',
            field=models.CharField(choices=[('SP', 'Single Page'), ('DP', 'Double Page')], default='SP', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('B&W', 'Black and White'), ('Color', 'Color')], default='B&W', max_length=5),
        ),
    ]
