# Generated by Django 4.2.6 on 2023-11-21 12:28

import Shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_rename_type_order_colortype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ColorType',
            field=models.CharField(choices=[('B&W', 'Black and White'), ('Color', 'Color')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='UploadFile',
            field=models.FileField(blank=True, null=True, upload_to=Shop.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=225),
        ),
    ]
