# Generated by Django 4.2.6 on 2023-11-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_alter_order_colortype_alter_order_uploadfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackAndWhitePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Single_Page_Cost', models.IntegerField()),
                ('Double_Page_Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ColorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Single_Page_Cost', models.IntegerField()),
                ('Double_Page_Cost', models.IntegerField()),
            ],
        ),
    ]
